### ISSUE TITLE
Could not locate bindings file

### ISSUE THREAD

**Issue by MarkTiedemann** [MarkTiedemann/node-win-proc-info#1]
Based on: [https://github.com/sindresorhus/tasklist/issues/15#issuecomment-404140214](https://github.com/sindresorhus/tasklist/issues/15#issuecomment-404140214)

**Comment by MarkTiedemann** [comment]
@vaidyaanand Could you please post the output of the following commands to help me diagnose the issue?

```cmd
yarn add win-proc-info@0.0.2
node -p "require('win-proc-info')(process.pid)"
```

**Comment by vaidyaanand** [comment]
I have run the above code following is the o/p: 
```
{ pageFaultCount: 13303,
  pagefileUsage: 10797056,
  peakPagefileUsage: 11149312,
  peakWorkingSetSize: 21524480,
  privateUsage: 10797056,
  quotaNonPagedPoolUsage: 13416,
  quotaPagedPoolUsage: 154856,
  quotaPeakNonPagedPoolUsage: 15136,
  quotaPeakPagedPoolUsage: 182824,
  workingSetSize: 21524480 }
(node:2180) Warning: N-API is an experimental feature and could change at any time.
```

**Comment by vaidyaanand** [comment]
But, when I run it inside application, I am getting following error:

![error](https://user-images.githubusercontent.com/22315535/42613290-d90a8d34-85bd-11e8-8122-5d3f31a2a2e9.png)
Following are the steps I am doing:
1. yarn add win-proc-info@0.0.2
in window.js (rendered file of [electron.js](https://electronjs.org/))
`var procInfo = require('win-proc-info');`
Run application:
cmd->` electron app.js`

**Comment by MarkTiedemann** [comment]
So you are trying to use the native module in the renderer thread of the browser? I don't think that could possibly work.

I suggest you try using it in the main thread, and then send the results to the renderer thread via IPC.

But I don't have much experience with Electron, so please test this and let me know whether it works. :)

**Comment by vaidyaanand** [comment]
Yes, I have got the clue of it earlier, will execute it in the main process and let you know.
Thanks

**Comment by MarkTiedemann** [comment]
Okay. Let me know if there are any other issues.

Closing for now.
